name: Go on Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest

    - name: Set up Go
      uses: actions/setup-go@latest
      with:
        # Change your go version as needed
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@latest
      with:
        name: go-app
        path: |
            .
  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      pages: write
    
    steps:
      - name: Downloading Artifact
        uses: actions/download-artifact@latest
        with:
          name: go-app
          path: .
          
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5    
        id: deploy-to-pages
